### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Game-Unity** [flaming-cl/editorjs-math#3]
Hi, I'm a bit confused about how to install this. I included the master/dist/bundle.js file in my project and added 
```
math: {
      class:  Math,
    },
```
But I get the error: 

editorjs.js:2 Uncaught TypeError: Math.floor is not a function
    at o.value (editorjs.js:2)
    at editorjs.js:2
    at editorjs.js:2

**Comment by flaming-cl** [comment]
1. Why this happened:
It happened because of an inappropriate webpack setting, which packed the plugin as window.Math. 
So the plugin overlapped with the Javascript Math library, and your program showed 「TypeError: Math.floor is not a function」
2. How to install the plugin:
I've updated the readme file, and you can follow it to install the plugin via NPM or CDN.
